services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: reale_estate_api
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=real_estate_db
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRATION=1d
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=real_estate_db
    container_name: reale_estate_postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
